# -*- coding: utf-8 -*-
"""ppg_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZF9DYen6WaGXTnjyHwYNyOME5DXP6Xq
"""

code = '''
import streamlit as st
import pandas as pd

def load_ppg_data():
    return pd.read_csv("ppg_sample.csv")

def app():
    st.title("❤️ PPG Signal Viewer")

    df = load_ppg_data()

    st.write("### 📊 Sample PPG Signal (10 seconds)")
    st.line_chart(df['ppg_amplitude'])

    st.write("### 📈 Signal Summary")
    st.dataframe(df.describe())

    st.write("### 🧠 Quick Insight")
    avg_amp = df['ppg_amplitude'].mean()
    st.success(f"Average PPG amplitude: {avg_amp:.4f}")

if __name__ == "__main__":
    app()
'''

with open("ppg_app.py", "w") as f:
    f.write(code)

print("✅ File saved: ppg_app.py")
